let message: { [key: string]: string };
message = {
  SUCCESS_MESSAGE: "CONGRATULATION, YOUR ADDRESS IS VALID",
  ERROR_MESSAGE: "SORRY, YOUR ADDRESS IS NOT VALID",
  ERROR_TOKEN: "SORRY, YOUR TOKEN IS NOT VALID",
  ERROR_IP: "SORRY, YOUR IP IS NOT VALID",
};

export default message;
